name: CI

on:
  push:
    branches: [ master, topic2]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: [ '5432:5432' ]
        env:
          username: postgres
          password: ${{ secrets.PG_PASSWORD }}
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Setup ruby
        uses: ruby/setup-ruby@c106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.7.1
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: install dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler

      - name: install gems
        run: |
          bundle install --jobs 4 --retry 3

      - name: prepare database
        run: |
          bundle exec rails db:prepare
          
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
        run: |
          bundle exec rspec spec


